# Generated by Django 6.0.2 on 2026-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baby', 'Baby Care'), ('firstaid', 'First Aid'), ('personal', 'Personal Care'), ('medicine', 'Medicines'), ('device', 'Health Devices')], default='medicine', max_length=20),
        ),
    ]
